// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_pfUtCvuZHUKr_a1NJq23xZflRfSVoCo',
    appId: '1:873894013264:web:9247b73c7d4043ededa455',
    messagingSenderId: '873894013264',
    projectId: 'fasalplanner',
    authDomain: 'fasalplanner.firebaseapp.com',
    storageBucket: 'fasalplanner.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPbh75p04XxyZ5oYzw4911AZH87mtZLPg',
    appId: '1:873894013264:android:ed4c682aaf30b02ceda455',
    messagingSenderId: '873894013264',
    projectId: 'fasalplanner',
    storageBucket: 'fasalplanner.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEBJ7ZewUmY09Gf_VtF3W13T3tIhArbQk',
    appId: '1:873894013264:ios:1d07fa3f87107a77eda455',
    messagingSenderId: '873894013264',
    projectId: 'fasalplanner',
    storageBucket: 'fasalplanner.firebasestorage.app',
    iosBundleId: 'com.example.madProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEBJ7ZewUmY09Gf_VtF3W13T3tIhArbQk',
    appId: '1:873894013264:ios:1d07fa3f87107a77eda455',
    messagingSenderId: '873894013264',
    projectId: 'fasalplanner',
    storageBucket: 'fasalplanner.firebasestorage.app',
    iosBundleId: 'com.example.madProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_pfUtCvuZHUKr_a1NJq23xZflRfSVoCo',
    appId: '1:873894013264:web:bb92acce6413bf2aeda455',
    messagingSenderId: '873894013264',
    projectId: 'fasalplanner',
    authDomain: 'fasalplanner.firebaseapp.com',
    storageBucket: 'fasalplanner.firebasestorage.app',
  );
}
